# 主题配置
ZSH_THEME="ys"

# 插件配置
plugins=(git z wd extract colored-man-pages zsh-syntax-highlighting)
# git                       最常用插件，git 相关
# z                         按照使用频率排序曾经进过的目录，进行模糊匹配
# wd                        通过设置 tag，快速切换目录
# extract                   'x'命令，支持自动识别压缩格式并将其解压
# colored-man-pages         'man'帮助文档页面开启高亮显示
# zsh-syntax-highlighting   oh-my-zsh 命令行语法高亮插件

# 历史记录
HIST_STAMPS="yyyy-mm-dd"        # 时间戳 "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
export HISTSIZE=100000          # 保存 100000 条记录
export HISTCONTROL=ignoredups   # 不记录重复的命令

# 其他配置
# CASE_SENSITIVE="true"         # 命令补全区分大小写，默认不区分
HYPHEN_INSENSITIVE="true"       # 命令补全不区分'_'、`-`，建议启用
DISABLE_AUTO_UPDATE="true"      # 不进行自动更新检查（每两个星期）
# export UPDATE_ZSH_DAYS=13     # 修改自动更新检查的周期，单位为天
# DISABLE_LS_COLORS="true"      # 禁用 ls 命令显示颜色
# DISABLE_AUTO_TITLE="true"     # 禁用 oh-my-zsh 自动设置终端标题
# ENABLE_CORRECTION="true"      # 启用命令自动更正，不好用
# COMPLETION_WAITING_DOTS="true"# 在等待命令补全时显示红点

# 加载 oh-my-zsh.sh
export ZSH=~/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

# function path，可使用 autoload 加载
fpath=(~/.zsh_func $fpath)

# xterm-256color
if [ $TERM = 'xterm' ]; then
    export TERM=xterm-256color
fi

# 默认编辑器 vim
export EDITOR=vim
export SVNEDITOR=vim
alias vi='vim'

# autoload
alias autoload='autoload -Uz'
alias al='autoload'
# src
alias src='source'

# zshedit | zshload
alias zshedit='vim ~/.zshrc'
alias zshload='source ~/.zshrc'
# zshfuncedit
function zshfuncedit() {
    vim ~/.zsh_func/$1
}

# echo
alias echo='echo -e'

# curl
alias curl='curl -s'

# grep
alias grep='grep -P --color'
alias egrep='egrep --color'

# diff
alias diff='diff -u'

# ps
alias ps='ps -ef'

# date_show
alias date_show='date "+%A %F %T %Z"'
# catconf
alias catconf='egrep -v "^\s*$|^\s*#"'
# catfunc
alias catfunc='typeset -f'

# getip
function getip() {
    local ip_info=$(curl -sL ip.chinaz.com/getip.aspx | sed -r "s/^\{ip:'(.*)',address:'(.*)'\}$/\1|\2/g")
    local my_ip=$(echo ${ip_info} | awk -F'|' '{print $1}')
    local my_loc=$(echo ${ip_info} | awk -F'|' '{print $2}')
    echo -e "\e[37mIP:\e[0m ${my_ip}\t\e[37m位置:\e[0m ${my_loc}"
}

# http/https 代理
proxy=http://127.0.0.1:1080
export http_proxy=$proxy
export https_proxy=$proxy
export no_proxy="localhost, 127.0.0.1, ::1, ip.cn, chinaz.com"
# unset proxy
alias unset_proxy='unset http_proxy https_proxy ftp_proxy no_proxy'
